language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t timsavage2112/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true timsavage2112/docker-react npm run test